In [1]:
import os, sys
# go one level up so "modules" is importable as a package
repo_root = os.path.abspath("..")
if repo_root not in sys.path:
    sys.path.append(repo_root)
# verify where we are
print("CWD:", os.getcwd())
print("Repo root on sys.path:", repo_root in sys.path)


CWD: /users/project1/pt01183/Building-height-width/street_view
Repo root on sys.path: True


In [2]:
import geopandas as gpd
import rasterio
from rasterio.mask import mask
import numpy as np
import folium
import json
import matplotlib.pyplot as plt
from shapely.geometry import box
from rasterio.windows import from_bounds
from rasterio.plot import show
import random
from shapely.geometry import box
import osmnx as ox
import os
import os
import requests
import shutil
from PIL import Image, ImageFile
from geojson import Feature, FeatureCollection  # Add this import
import math
import torch
import transformers
import fiona
print("Fiona drivers GPKG available?", "GPKG" in fiona.supported_drivers)

Fiona drivers GPKG available? True


In [3]:
import torch
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

CUDA available: True
NVIDIA A100 80GB PCIe


In [4]:
import os, sys, importlib
repo_root = "/users/project1/pt01183/Building-height-width"
if repo_root not in sys.path:
    sys.path.append(repo_root)

# Preferred: set env var and let config read it
os.environ["PROJECT_DIR"] = "/users/project1/pt01183/Building-height-width"


In [5]:
# Your Google Street View API key
import os
os.environ["GSV_API_KEY"] = "AIzaSyBU4OGgIVAktImTaC-uYcXJN-vL-LE3jtM"

In [44]:
# 2) reload config, then segmentation, then process_data (in this order)

import street_view.segmentation_images as seg
importlib.reload(seg)

import street_view.process_data as pd
importlib.reload(pd)

import street_view.road_network as rn


## Road network

In [45]:
import road_network as rn, inspect
print("Loaded from:", rn.__file__)
print("Function source:\n", inspect.getsource(rn.get_road_network))


Loaded from: /users/project1/pt01183/Building-height-width/street_view/road_network.py
Function source:
 def get_road_network(city, bbox=None):
    print(f"Fetching road network for city: {city}")
    cf = '["highway"~"primary|secondary|tertiary|residential|primary_link|secondary_link|tertiary_link|living_street|service|unclassified"]'

    try:
        if bbox:
            G = ox.graph_from_bbox(bbox[3], bbox[1], bbox[2], bbox[0], simplify=True, custom_filter=cf)
        else:
            G = ox.graph_from_place(city, simplify=True, custom_filter=cf)
    except Exception:
        return gpd.GeoDataFrame()

    # collapse reverse duplicates: keep one direction per physical segment
    unique_roads = set()
    G_simplified = G.copy()
    for u, v, key in list(G.edges(keys=True)):
        if (v, u) in unique_roads:
            G_simplified.remove_edge(u, v, key)
        else:
            unique_roads.add((u, v))
    G = G_simplified

    # project to a metric CRS (meters) and return edge

In [9]:
import importlib, road_network as rn
importlib.reload(rn)

<module 'road_network' from '/users/project1/pt01183/Building-height-width/street_view/road_network.py'>

In [47]:
roads = rn.get_road_network(CITY_NAME)
print("edges:", len(roads), roads.crs)
print(roads["highway"].value_counts().head(15))
print("total km:", roads.length.sum()/1000)


Fetching road network for city: Gdańsk, Poland
edges: 38034 EPSG:32634
highway
service                         22492
residential                      7859
tertiary                         2569
living_street                    2175
secondary                        1240
primary                           619
unclassified                      556
[residential, service]            210
primary_link                       83
secondary_link                     77
[living_street, service]           71
tertiary_link                      30
[living_street, residential]       30
[unclassified, residential]         6
[unclassified, service]             5
Name: count, dtype: int64
total km: 2275.9746868431066


In [26]:
CITY_NAME = "Gdańsk, Poland"
SPACING_M = 50
points_path = "/users/project1/pt01183/Building-height-width/data/points.gpkg"


# 2) sample points every N meters (projected)
pts_proj = select_points_on_road_network_projected(roads, N=SPACING_M)
print("sampled points (proj):", len(pts_proj), pts_proj.crs)

# 3) convert to WGS84 for Street View
pts_wgs84 = pts_proj.to_crs(4326)

# 4) minimal schema: id + geometry
pts_min = pts_wgs84[["id", "geometry"]].copy()

# 5) save (overwrite)
if os.path.exists(points_path):
    os.remove(points_path)
pts_min.to_file(points_path, layer="points", driver="GPKG")
print("Saved:", points_path, "rows:", len(pts_min), "CRS:", pts_min.crs)

sampled points (proj): 50363 EPSG:32634
Saved: /users/project1/pt01183/Building-height-width/data/points.gpkg rows: 50363 CRS: EPSG:4326


## Select area by map

In [6]:
import leafmap

# Center on Gdańsk; draw ONE rectangle, then run the next cell
m = leafmap.Map(center=[54.3520, 18.6466], zoom=13, height="600px")
m.add_basemap("SATELLITE")
m

Map(center=[54.352, 18.6466], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoo…

In [7]:
# Read the bbox you drew (west, south, east, north)
bbox = m.user_roi_bounds(decimals=8)  # [w, s, e, n]
print("bbox:", bbox)
use_bbox = bool(bbox)

bbox: [18.650923, 54.350817, 18.65809, 54.353293]


In [10]:
import os, sys, importlib, random
import geopandas as gpd
from shapely.geometry import box

city = "Gdańsk, Poland"

# (a) Roads (use bbox to speed things up)
roads_all = rn.get_road_network(city, bbox=bbox if use_bbox else None)
if roads_all.empty:
    raise SystemExit("No roads found — try a different bbox or city.")
print("Roads:", len(roads_all), "CRS:", roads_all.crs)

# (b) If you drew a bbox, clip roads to it (roads_all is already in a projected CRS)
if use_bbox:
    roi_wgs84 = gpd.GeoDataFrame(geometry=[box(*bbox)], crs=4326)
    roi_proj  = roi_wgs84.to_crs(roads_all.crs)
    roi_geom  = roi_proj.geometry.iloc[0]
    roads = roads_all[roads_all.geometry.intersects(roi_geom)].copy()
    print("Roads in bbox:", len(roads))
else:
    roads = roads_all

# (c) Sample points along roads every N meters (projected CRS)
N = 35  # meters
pts = rn.select_points_on_road_network(roads, N=N)
print("Points generated:", len(pts))


# (e) Convert to WGS84 for the Street View calls
pts_wgs84 = pts.to_crs(4326)

# (f) Small random subset (e.g., first try 10)
k = min(10, len(pts_wgs84))
gdf_small = pts_wgs84.sample(k, random_state=42).reset_index(drop=True).copy()

# Ensure 'id' exists and mark for QA overlays
gdf_small["id"] = gdf_small.index.astype(int)
gdf_small["save_sample"] = True

print("Subset points:", len(gdf_small))
gdf_small.head()

Fetching road network for city: Gdańsk, Poland
Roads: 77 CRS: EPSG:32634
Roads in bbox: 77
Points generated: 100
Subset points: 10


,geometry,road_index,id,save_sample
0,POINT (18.65172 54.35206),"(2320875684, 9747558161, 0)",0,True
1,POINT (18.65723 54.35251),"(9983467305, 9983467307, 0)",1,True
2,POINT (18.65635 54.35321),"(1446281525, 2617194533, 0)",2,True
3,POINT (18.65131 54.35114),"(1119413903, 1119354422, 0)",3,True
4,POINT (18.65166 54.35116),"(1119354437, 11870274402, 0)",4,True


In [11]:
import leafmap
import geopandas as gpd

def _to_wgs84(gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    if gdf.crs is None or gdf.crs.to_epsg() != 4326:
        return gdf.to_crs(4326)
    return gdf

# Convert to WGS84 for web mapping
roads_wgs84 = _to_wgs84(roads)
pts_all_wgs84 = _to_wgs84(pts_wgs84)

# Map center
if len(pts_all_wgs84):
    center = [pts_all_wgs84.geometry.y.mean(), pts_all_wgs84.geometry.x.mean()]
else:
    c = roads_wgs84.geometry.unary_union.centroid
    center = [c.y, c.x]

m = leafmap.Map(center=center, zoom=16, height="650px")
m.add_basemap("CartoDB.Positron")
m.add_basemap("SATELLITE")

# Roads layer
m.add_gdf(
    roads_wgs84,
    layer_name="Roads (clipped)",
    style={"color": "#00BCD4", "weight": 3, "opacity": 0.9}
)

# All points layer (with clustering for performance if many points)
popup_cols = [c for c in ["road_angle"] if c in pts_all_wgs84.columns]
m.add_gdf(
    pts_all_wgs84,
    layer_name="All Points (every N m)",
    style={"color": "#FF5722", "fillColor": "#FF5722", "radius": 4, "opacity": 1, "fillOpacity": 0.9},
    popup_fields=popup_cols if popup_cols else None,
    zoom_to_layer=True,
    enable_clustering=True,   # toggle to False if you prefer plain markers
)

m


Map(center=[54.35204972964685, 18.654689119585836], controls=(ZoomControl(options=['position', 'zoom_in_text',…

In [14]:
# 0) Imports + make sure we load your latest code
import os, importlib, geopandas as gpd

from street_view.road_network import get_road_network
import street_view.segmentation_images as seg     # defines save_all_products palettes, etc.
import street_view.process_data as pd             # defines download_images_for_points(...)

importlib.reload(seg)
importlib.reload(pd)

2025-10-31 12:42:00.897591: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-10-31 12:42:03.962524: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1761910924.311127 2032709 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1761910924.557367 2032709 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1761910926.479138 2032709 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

<module 'street_view.process_data' from '/users/project1/pt01183/Building-height-width/street_view/process_data.py'>

In [15]:
import os, geopandas as gpd
from street_view.process_data import download_images_for_points

download_images_for_points(
    gdf=gdf_small,
    access_token=os.environ["GSV_API_KEY"],
    max_workers=4,
    cut_by_road_centres=False,   # <-- no road-centre logic
    city=CITY_NAME,
    file_name="run1",
    fov=90,
    pitch=25
)

NameError: name 'CITY_NAME' is not defined

In [17]:
from numpy import load

In [18]:
data = load('/users/project1/pt01183/Building-height-width/data/lines/6_196.npz')
lst = data.files
for item in lst:
    print(item)
    print(data[item])

nlines
[[[192.61163712 348.5187912 ]
  [249.26809311 348.81763458]]

 [[252.9930687  302.55792618]
  [196.51861191 302.63977051]]

 [[173.0556488  302.15450287]
  [133.16040039 302.78512955]]

 ...

 [[348.33359847 267.20644081]
  [348.33377797 267.19033743]]

 [[197.74471283 272.00483322]
  [190.57454437 283.37994721]]

 [[358.19127911  72.48074807]
  [358.2503735   71.97020698]]]
nscores
[0.99989367 0.99987876 0.99985754 0.9997851  0.9997762  0.9997527
 0.9997398  0.9997285  0.99971133 0.99968576 0.9996828  0.99968123
 0.9996805  0.999678   0.9996755  0.99967265 0.9996395  0.99963117
 0.99962795 0.99960893 0.9996069  0.9995981  0.999571   0.9995653
 0.9995431  0.99952984 0.9995166  0.9995086  0.99950695 0.9995048
 0.9994815  0.9994803  0.9994592  0.9994466  0.99944395 0.99940276
 0.9993948  0.9993569  0.9993358  0.9993325  0.99932766 0.99932635
 0.9993228  0.99931884 0.99931765 0.999316   0.9993119  0.9993069
 0.9992969  0.9992951  0.9992943  0.9992729  0.9992638  0.99925655
 0.99923